# Generated by Django 4.1.3 on 2023-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
