# Generated by Django 4.1.3 on 2023-01-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='service/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
