# Generated by Django 4.1.3 on 2023-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_company_created_company_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
