# Generated by Django 4.1.3 on 2023-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_company_active_alter_faqs_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousproject',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('blue', 'BLUE'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('sky', 'SKY'), ('mof', 'MOF'), ('pink', 'PINK'), ('gray', 'GRAY')], max_length=50, null=True),
        ),
    ]
