# Generated by Django 4.1.3 on 2023-01-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_customer_email'),
        ('service', '0003_package_created_package_updated_service_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.package')),
            ],
        ),
    ]
