# Generated by Django 4.1.3 on 2023-01-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
